//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public long BarId { get; set; }
        public System.DateTime PriceDate { get; set; }
        public int BarInterval { get; set; }
        public int BarDataType { get; set; }
        public long StartTimestamp { get; set; }
        public long EndTimestamp { get; set; }
        public float BarMin { get; set; }
        public float BarMax { get; set; }
        public int BarRange { get; set; }
        public float BarOpen { get; set; }
        public float BarClose { get; set; }
        public float BarMedian { get; set; }
        public float BarAvg { get; set; }
        public string InstrumentCode { get; set; }
        public string Maturity { get; set; }
    }
}
