//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPriceBar
    {
        public int DailyBarDataId { get; set; }
        public string InstrumentCode { get; set; }
        public System.DateTime PriceDate { get; set; }
        public Nullable<float> BarMin { get; set; }
        public Nullable<float> BarMax { get; set; }
        public Nullable<float> BarOpen { get; set; }
        public Nullable<float> BarClose { get; set; }
    }
}
