//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegressionJobBar
    {
        public int RegressionJobId { get; set; }
        public int BarIndex { get; set; }
        public Nullable<float> BarMin { get; set; }
        public Nullable<float> BarMax { get; set; }
    }
}
