//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegressionJobTickData
    {
        public long RegressionJobTickDataId { get; set; }
        public int RegressionJobId { get; set; }
        public Nullable<int> BarIndex { get; set; }
        public Nullable<float> Ask { get; set; }
        public Nullable<float> AskQty { get; set; }
        public Nullable<float> Bid { get; set; }
        public Nullable<float> BidQty { get; set; }
    }
}
