//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegressionJobTradePosition
    {
        public int RegressionJobId { get; set; }
        public string TradePositionType { get; set; }
        public int Reference { get; set; }
        public Nullable<float> Price { get; set; }
        public string Direction { get; set; }
        public Nullable<float> Lots { get; set; }
        public Nullable<float> Target { get; set; }
        public Nullable<float> Stop { get; set; }
        public Nullable<int> BarIndex { get; set; }
        public int RegressionTradeSignalId { get; set; }
    }
}
