//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegressionJob
    {
        public int RegressionJobId { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public string InstrumentCode { get; set; }
        public Nullable<System.DateTime> RegressionStartDate { get; set; }
        public Nullable<System.DateTime> RegressionEndDate { get; set; }
        public Nullable<int> RegressionBarInterval { get; set; }
        public Nullable<bool> RegressionIsDaily { get; set; }
        public string RegressionStrategyName { get; set; }
        public string RegressionMicroEnvironment { get; set; }
        public string RegressionMacroEnvironment { get; set; }
        public string RegressionIntraDayEnvironment { get; set; }
        public string JobStatus { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
        public string RegressionDisplayName { get; set; }
    }
}
