//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATSYS.TradingModel.DataEntitySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingTickData
    {
        public long PriceDataId { get; set; }
        public Nullable<System.DateTime> PriceDate { get; set; }
        public string InstrumentCode { get; set; }
        public string Maturity { get; set; }
        public Nullable<long> Timestamp { get; set; }
        public Nullable<float> BestAsk { get; set; }
        public Nullable<float> BestAskQty { get; set; }
        public Nullable<float> BestBid { get; set; }
        public Nullable<float> BestBidQty { get; set; }
        public Nullable<float> Open { get; set; }
        public Nullable<float> High { get; set; }
        public Nullable<float> Low { get; set; }
        public Nullable<float> Close { get; set; }
        public Nullable<float> ImpliedAsk { get; set; }
        public Nullable<float> ImpliedAskQty { get; set; }
        public Nullable<float> ImpliedBid { get; set; }
        public Nullable<float> ImpliedBidQty { get; set; }
        public Nullable<float> LastTraded { get; set; }
        public Nullable<float> LastTradedQty { get; set; }
        public Nullable<float> Settlement { get; set; }
        public Nullable<float> TotalTradedQty { get; set; }
    }
}
